[project]
name = "cpe-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.0",
    "nltk>=3.9.1",
    "pandas>=2.3.1",
    "wordcloud>=1.9.4",
]
